- name: "create directory"
  file:
    path: ~/tmp
    mode: 0755
    state: directory

- name: "create directory"
  file:
    path: ~/web
    mode: 0755
    state: directory

- name: "copy files over to instance"
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/tmp/artifact.tar.gz
    backup: yes

- name: "install tar and gzip"
  become: true
  command: |
    apt-get install tar gzip -y

# - name: "extract backend file"
#   become: true
#   command: |
#     tar -xzvf ~/tmp/artifact.tar.gz -C ~/web/

- name: "Extract Artifact"
  become: true
  unarchive:
    src: ~/tmp/artifact.tar.gz
    dest: ~/web/

- name: "start backend with pm2"
  become: true
  command: |
    npm install
    pm2 stop default
    pm2 start -- start
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: "./migrations"
    TYPEORM_MIGRATIONS: "./migrations/*.js"
    TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"

