- name: "create directory"
  file:
    path: ~/tmp
    mode: 0755
    state: directory

- name: "create directory"
  file:
    path: ~/web
    mode: 0755
    state: directory

- name: "copy files over to instance"
  copy:
    src: ~/project/artifact.tar.gz
    dest: ~/tmp/artifact.tar.gz
    backup: yes

- name: "install tar and gzip"
  become: true
  command: |
    apt-get install tar gzip -y

- name: "extract backend file"
  become: true
  command: |
    tar -xzvf ~/tmp/artifact.tar.gz -C ~/web

- name: "start backend with pm2"
  become: true
  command: |
    npm install
    pm2 stop default
    pm2 start -- start

